return {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    branch = 'main',
    lazy = false,
    config = function()
        require "nvim-treesitter.configs".setup({
            ensure_installed = {
                "zig",
                "lua",
                "luau",
                "javascript",
                "typescript",
                "c",
                "php",
                "css",
                "nix",
                "desktop",
                "fish",
                "bash",
                "json",
                "jsonc",
                "dockerfile",
                "xml",
                "python",
                "rust",
                "html",
                "graphql",
                "solidity",
                "yuck",
                "rasi",
                "scss",
                "markdown",
                "markdown_inline",
                "yaml",
                "toml",
                "ini",
                "diff",
                "git_rebase",
                "git_config",
                "gitattributes",
                "gitcommit",
                "gitignore",
                "nginx",
                "hyprlang",
                "go"
            },
            sync_install = false,
            indent = {
                enable = true,
            },
            auto_install = false,
            highlight = {
                enable = true,
                additional_vim_regex_highlighting = true,
            },
        })
    end
}
